name: API Test Suite CI / CD Execution

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment"
                required: true
                type: choice
                options:
                    - qa
                default: "qa"
            suite:
                description: "Suite"
                required: true
                type: choice
                options:
                    - "regression"
                    - "sanity"
                default: "regression"
            instances:
                description: "Parallel instances"
                required: true
                type: choice
                options:
                    - "1"
                    - "2"
                    - "3"
                    - "4"
                default: "1"

jobs:
    test-execution:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Execute test suite
              run: |
                  ENV=${{ github.event.inputs.environment }} SUITE=${{ github.event.inputs.suite }} npm run test --maxWorkers=${{ github.event.inputs.instances }}
              continue-on-error: true

            - name: Upload Allure results
              uses: actions/upload-artifact@v3
              with:
                name: allure-results
                path: ./allure-results