name: Parallel Shard Execution

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - "qa"
        default: "qa"
      suite:
        description: "Suite"
        required: true
        type: choice
        options:
          - "regression"
          - "sanity"
        default: "regression"
      instances:
        description: "Parallel instances"
        required: true
        type: choice
        options:
          - "1"
          - "2"
          - "3"
          - "4"
        default: "1"

jobs:

  build-base-image:
    name: Build Base Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Base Image
      run: |
        docker build -t base-image -f ./shard-workspace/Dockerfile_base .

  build-and-test:
    name: Build and Test
    needs: build-base-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [1, 2]  # Add more container numbers if needed
    env:
      ENV: ${{ github.event.inputs.environment }}
      SUITE: ${{ github.event.inputs.suite }}
      INSTANCES: ${{ github.event.inputs.instances }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v2

    - name: Generate Dockerfiles
      run: |
        bash scripts/pipeline-shard-execution.sh

    - name: Build Docker Image
      run: |
        docker build --cache-from=base-image -t docker-${{ matrix.container }} -f ./shard-workspace/Dockerfile_container_${{ matrix.container }} .

    - name: Run Docker Container
      run: |
        docker run \
          -e ENV=${{ env.ENV }} \
          -e SUITE=${{ env.SUITE }} \
          -e INSTANCES=${{ env.INSTANCES }} \
          -e SLACK_WEBHOOK_URL=${{ env.SLACK_WEBHOOK_URL }} \
          docker-${{ matrix.container }}